export const GET_INFORMATION_MOVIE_REQUEST = "GET_INFORMATION_MOVIE_REQUEST"
export const GET_INFORMATION_MOVIE_SUCCESS = "GET_INFORMATION_MOVIE_SUCCESS"
export const GET_INFORMATION_MOVIE_FAIL = "GET_INFORMATION_MOVIE_FAIL"
