export const GET_USER_INFORMATION_REQUEST = "GET_USER_INFORMATION_REQUEST";
export const GET_USER_INFORMATION_SUCCESS = "GET_USER_INFORMATION_SUCCESS";
export const GET_USER_INFORMATION_FAIL = "GET_USER_INFORMATION_REQUEST";
