export const GET_USER_INFORMATION_REQUEST = "GET_USER_INFORMATION_REQUEST";
export const GET_USER_INFORMATION_SUCCESS = "GET_USER_INFORMATION_SUCCESS";
export const GET_USER_INFORMATION_FAIL = "GET_USER_INFORMATION_REQUEST";

export const UPDATE_USER_INFORMATION_REQUEST = "UPDATE_USER_INFORMATION_REQUEST";
export const UPDATE_USER_INFORMATION_SUCCESS = "UPDATE_USER_INFORMATION_SUCCESS";
export const UPDATE_USER_INFORMATION_FAIL = "UPDATE_USER_INFORMATION_FAIL";
